services:
  db:
    image: postgres:16-alpine
    container_name: pipeline_db
    environment:
      POSTGRES_DB: pipedb
      POSTGRES_USER: pipeuser
      POSTGRES_PASSWORD: pipepass
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  tomcat:
    build: .
    container_name: pipeline_app
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  db_data:
